name: Парсер паспортов

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Установка пакетов (OCR)
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-rus poppler-utils

    - name: Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests gspread oauth2client

    - name: Запуск
      env:
        BITRIX_WEBHOOK: ${{ secrets.BITRIX_WEBHOOK }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py
